### PR TITLE
feat: removal of channel override

### PR DESCRIPTION
**Pull request by ayusham001**
/claim #265

### CODE REVIEW

**Comment by simonflk** [comment]
Was there already an unsetChannel method? It's not in the docs

**Comment by ayusham001** [comment]
> Was there already an unsetChannel method? It's not in the docs

Yes, it was for android and ios both.

**Comment by ayusham001** [comment]
Hi @simonflk, do you have any feedback or suggested changes?

**Comment by simonflk** [comment]
@ayusham001, the changes here have me puzzled. It appears that @riderx [added the `unsetChannel()`](https://github.com/Cap-go/capacitor-updater/commit/935c01be27f01e627efae941be11c6b89c1d8104) method just last week. Since I haven't had the opportunity to test it and I'm not well-versed in this codebase, could you clarify if this update fixes an existing issue or adds new functionality?

It might also be useful to include this in [the documentation](https://capgo.app/docs/plugin/api/#setchanneloptions). I noticed that the `triggerAutoUpdate` option for `setChannel` isn't documented either.

**Comment by ayusham001** [comment]
> @ayusham001, the changes here have me puzzled. It appears that @riderx [added the `unsetChannel()`](https://github.com/Cap-go/capacitor-updater/commit/935c01be27f01e627efae941be11c6b89c1d8104) method just last week. Since I haven't had the opportunity to test it and I'm not well-versed in this codebase, could you clarify if this update fixes an implementation issue or adds new functionality?
> 
> It might also be useful to include this in [the documentation](https://capgo.app/docs/plugin/api/#setchanneloptions). I noticed that the `triggerAutoUpdate` option for `setChannel` isn't documented either.

The updates to the unsetChannel function address an implementation issue by allowing unsetting specific channels and adding new functionality for enhanced flexibility.

**Pull request closed without merging**
