### PR TITLE
More robust disposal of streams

### PR DESCRIPTION
**Pull request by DinosaurDad**
I was experiencing a stream leak in some scenarios, so I tightened up the resource disposal. This update is working successfully here.

### CODE REVIEW

**Comment by riderx** [comment]
Thanks for this change, it look good, my only question is why you don't close anymore stream ?

**Comment by DinosaurDad** [comment]
This approach is what Java calls try-with-resources, and it automatically closes the streams for you. No `finally` needed, and no need to close explicitly.

**Comment by riderx** [comment]
Ok nice !

**Comment by riderx** [comment]
Can your lint your code, to pass the PR test ?

**Pull request merged**
