### PR TITLE
fix: invalid sessionKey decode + android invalid checksum

### PR DESCRIPTION
**Pull request by ludufre**
With a invalid Session Key the App crashes with: "Fatal error: Unexpectedly found nil while unwrapping an Optional value"

image

### CODE REVIEW

**Comment by ludufre** [comment]
@riderx those two commits fixes two issues:
- iOS: if provided a invalid sessionKey the apps crash. I've added a simple catch.
- Android: following iOS workflow, you not check the checksum from manual update. only for auto update/background update. So, I've disabled the checksum when calling downloadFinished().

**Comment by riderx** [comment]
Thanks @ludufre for the PR and fixing the bugs, 
i 100% agree with iOS fix !
For Android, why disabling checksum instead of enabling in iOS too?

**Comment by ludufre** [comment]
> For Android, why disabling checksum instead of enabling in iOS too?

Unfortunately I'm not experienced Object-C/Swift developer :/

**Comment by ludufre** [comment]
Has I can see, on Android the checksum have to be fixed too. On manual mode we not send the CRC to downloadFinised from download()

**Pull request merged**
