### PR TITLE
Update types

### PR DESCRIPTION
**Pull request by bosh-code**
Update the types and JSDocs for this plugin.

Contains "breaking" changes for any users using typescript as some of the interface names have changed and the usage will need to be updated, however this should have no effect on code execution.

Happy to discuss feedback.

### CODE REVIEW

**Comment by riderx** [comment]
Hey thanks for the update, i wonder why did you removed the licence in the file?

**Comment by bosh-code** [comment]
> Hey thanks for the update, i wonder why did you removed the license in the file?

No worries, as long as you are shipping the license with the package, which you are, there's nothing more that needs to be done. Its not standard practice to include license docs at the beginning of source files.

**Comment by riderx** [comment]
License is very important for the project.
This kind of thing cannot be done without discussion.
The current license requires this exact behavior to be done for the plugin.
Secondly, you removed only in one place, what is not really consistent.
So can you put it back ?

**Comment by riderx** [comment]
Here is the link if you want to learn about MPL:
https://www.mozilla.org/en-US/MPL/2.0/FAQ/
CleanShot 2024-03-18 at 23 27 09@2x

**Comment by bosh-code** [comment]
Sure no worries, added it back.

**Comment by riderx** [comment]
thanks !

**Pull request merged**
