### PR TITLE
Issue 163 fix sonarcloud issues

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
Hi @riderx 
I have fixed few of the issues as part of #163 
Would it require to merge these into master so that the updated list of issues start reflecting on sonarcloud server after my changes?

### CODE REVIEW

**Comment by riderx** [comment]
Seems sonarcloud only do diff check on PR, i looked in settings and nothing interesting

**Comment by ujwalkumar1995** [comment]
Hey @riderx 
I have pushed few changes to resolve some of the sonarcloud issues.
Could you please review and merge if they look good to you?

**Comment by riderx** [comment]
i let the CI pass and then i will merge it

**Comment by ujwalkumar1995** [comment]
Hey @riderx 
I see that your CI is failing.
Is something wrong with my changes?

**Comment by ujwalkumar1995** [comment]
Hey @riderx 
That was my bad. I went through the logs of the CI and found that I had implemented one of the checks in the wrong way. Have reverted that commit for now to see if the pipeline goes green. Could you please check now?

**Comment by arendjantetteroo** [comment]
@riderx @ujwalkumar1995 
This broke the building in my app:

`````````
import { CapacitorUpdater, latestVersion } from '@capgo/capacitor-updater';
Type error: '"@capgo/capacitor-updater"' has no exported member named 'latestVersion'. Did you mean 'LatestVersion'?
`
```

If you start changing names, this would be better reflected in a semver major? 
I don't expect my builds to fail when i update a patch version.

**Comment by ujwalkumar1995** [comment]
Hey @riderx 
If you want I can revert the commit with name change to typescript interfaces to unblock @arendjantetteroo.
What do you suggest @riderx?

**Comment by riderx** [comment]
yes, interface shouldn't change in minor.
please follow commit convention next time

**Comment by riderx** [comment]
sorry @arendjantetteroo that shouldn't have happen you are totally right

**Comment by ujwalkumar1995** [comment]
Hey @riderx 
Apologies for the inconvenience.
Do you want me to create a separate issue for this and fix it in a different PR?

**Comment by riderx** [comment]
@ujwalkumar1995 i recommend you to do a type alias in a next commit.
with the old name then everywhere the new type is used but both work.
and we will solve the sonar cloud message by saying it will be deprecated in next major

**Comment by ujwalkumar1995** [comment]
Hey @riderx 
Even with the old name on the alias, we will still have the sonar issue. Would it not be ok to just revert back to the old names on the interface?

**Comment by riderx** [comment]
i did reverted your changes.
the point of the good name everywhere with one alias lead to the current name is to have the sonarcloud issue only on the alias line, and we can tell to ignore it since it's just for retrocompt

**Pull request merged**
