### PR TITLE
adding milestones for notifying download on ios

### PR DESCRIPTION
**Pull request by YanisOUALAN**
This PR addresses an issue that was previously mentioned but overlooked in #400. It ensures that every 10% milestone is correctly notified when downloading an update on iOS.

### CODE REVIEW

**Comment by WcaleNieWolny** [comment]
@riderx @YanisOUALAN This has still not fixed the problem entirely. There are still 3 problems:

A) This isn't implemented in Android. Android has a fixed chunk size of 4KB but it DOESN'T guarantee that you will send all the stats correctly. For a small bundle (let's say 12kb) you are going to invoke the notify download at 33%, 66%, 100%. This is not good - this feature should be ported to Android

B) The stats lack order, download 70% is not always sent

https://github.com/user-attachments/assets/cf1a81d6-8ab2-479b-a971-19722555d3e1

C) You DO NOT scale the percentage - instead you hard cut it. This means that if someone interrupts the download at 80% there isn't going to be an indication of an interrupt in the stats


https://github.com/user-attachments/assets/b3bbbd0a-697d-423a-9410-5fe55a3f77f9

D) My changes to `notifyDownload` (The addition of `ignoreMultipleOfTen` hasn't been reverted)

**Comment by YanisOUALAN** [comment]
The disorganized sequence of events is caused by the `notifyDownload` function. This function, when called, asynchronously makes a request to the capgo API server to log the download_x statistic. It then waits for a server response. However, the speed of the user's internet connection can greatly delay this response, leading to requests being processed out of sequence.

For instance, consider the following scenario:
`.notifyDownload(10)`
While `.notifyDownload(10)` is awaiting a response, `.notifyDownload(20)` is called. Due to fluctuations in internet speed, the server might respond to `.notifyDownload(20)` before `.notifyDownload(10)`.

To fix this, we could adjust the process so that each download_x statistic must await the server's response before proceeding with the next download. However, this solution would reduce the overall download speed.

**Comment by YanisOUALAN** [comment]
I am investigating on the issues you mentioned @WcaleNieWolny

**Comment by YanisOUALAN** [comment]
> The disorganized sequence of events is caused by the `notifyDownload` function. This function, when called, asynchronously makes a request to the capgo API server to log the download_x statistic. It then waits for a server response. However, the speed of the user's internet connection can greatly delay this response, leading to requests being processed out of sequence.
> 
> For instance, consider the following scenario: `.notifyDownload(10)` While `.notifyDownload(10)` is awaiting a response, `.notifyDownload(20)` is called. Due to fluctuations in internet speed, the server might respond to `.notifyDownload(20)` before `.notifyDownload(10)`.
> 
> To fix this, we could adjust the process so that each download_x statistic must await the server's response before proceeding with the next download. However, this solution would reduce the overall download speed.

Or actually, we could implent a [DispatchQueue](https://developer.apple.com/documentation/dispatch/dispatchqueue), i am going to open another PR to adress fixes to the issues you mentioned and to implement the `DispatchQueue`.

**Comment by riderx** [comment]
I think we already have a dispatch queue for something else you can use it

**Pull request merged**
