### PR TITLE
Fixing signature issue to not prevent download when the signature is absent and disabled in config file

### PR DESCRIPTION
**Pull request by YanisOUALAN**

### CODE REVIEW

**Comment by riderx** [comment]
not sure to understand why you move it outside of the brakets?

**Comment by YanisOUALAN** [comment]
> not sure to understand why you move it outside of the brakets?

I apologize for the confusion; it appears there was a mix-up on my end. I moved that piece of code outside of the brackets while conducting some tests to better understand the issue we were having with the signature process. It wasn’t meant to be part of the final commit. I've reverted that change right away. Thanks for catching that!

**Comment by riderx** [comment]
so no changes then right?

**Comment by YanisOUALAN** [comment]
> so no changes then right?

I removed this piece of code in [8049672](https://github.com/Cap-go/capacitor-updater/pull/437/commits/804967255d79924932164451f2608ad7025e6b55)
```             
guard let signature = signature else {
                            throw CustomError.signatureNotProvided
                        }
```

That was what prevented the update of being started if signature was not provided

**Comment by riderx** [comment]
Yea but look in code change ahah that what i did too so the PR is empty ^^

**Comment by riderx** [comment]
I think we can close

**Pull request closed without merging**
