### PR TITLE
Make sure that chaning channel triggers autoupdate

### PR DESCRIPTION
**Pull request by WcaleNieWolny**
This makes sure that after channel change the auto updater gets called. If there are any updates in the new channel thee autoupdater will catch that and emit events as mentioned in [the issue](https://github.com/Cap-go/capacitor-updater/issues/231)

As for IOS, if this is an acceptable solution I can attempt to add something similar, but I do not have any way to test if IOS change works.

Here are the logs after my change:

image

The auto updater was called twice because I just ran:
```js
CapacitorUpdater.notifyAppReady()
CapacitorUpdater.setChannel({channel: "dev"})
```

so first it ran because of opening the app, and the second because I changed channel. If this double run is a problem I will introduce a check to make sure that the new channel is different then the old one

/claim #231

### CODE REVIEW

**Comment by WcaleNieWolny** [comment]
@riderx Can you please take a look at this? I would love your feedback

**Comment by riderx** [comment]
i think the set update is missing in this and this whole logic should be optional we cannot chamge the behavior like that

**Comment by WcaleNieWolny** [comment]
Very well, I will change this ASAP

**Comment by WcaleNieWolny** [comment]
Fixed merge conflicts

**Pull request merged**
