### PR TITLE
Feature Multi Delay

### PR DESCRIPTION
**Pull request by luca-sharryland**
this close issue #100
changes:
- update android dependencies (jcenter() deprecated)
- fix some conditions
- deprecate setDelay, internally calls setMultiDelay
- implement delay value for kind "background"

Now when a delay condition is met the app calls installNext function and reloads.
I've tested all delay values, in particular kill and background. I've found only two little problems: 
1 - in kill conditions only in ios, cause the app reloads and correctly installs new bundle but my js code (angular app ngOnInit) seems to be the old bundle one. After a second kill, it executes new bundle code.
I'm not a swift expert, so if you could debug this I will appreciate it.
2 - in android I've added a listener for appReloaded event to call notifyAppReady (I think is related to problem 1, so code in ngOnInit not reexecuted)

Tell me if something seems wrong to you
Thanks!

### CODE REVIEW

**Comment by riderx** [comment]
Thanks a lot @luca-sharryland for the work, it's a bit hard to review it like that, maybe can you split the work in different PR?
Like for the Lint/norm.

**Comment by luca-sharryland** [comment]
@riderx  Do you mean one commit for setMultiDelay ios and one for setMultiDelay Android?

**Comment by luca-sharryland** [comment]
@riderx ok seems to be resolved

**Comment by riderx** [comment]
@luca-sharryland seems there still not necessary change in [swift](https://github.com/Cap-go/capacitor-updater/pull/106/files#diff-577b0c76817479855ce5a638c3621bec3fc293a2d19776e76bcab0f3993f6080) can you run `npm run swiftlint -- --autocorrect --format` and commit ?

**Comment by luca-sharryland** [comment]
@riderx done!

**Comment by riderx** [comment]
@luca-sharryland thanks a lot, that perfect now, I cannot try it today but tomorrow probably

**Comment by luca-sharryland** [comment]
@riderx 
"in kill conditions only in ios, cause the app reloads and correctly installs new bundle but my js code (angular app ngOnInit) seems to be the old bundle one. After a second kill, it executes new bundle code.
I'm not a swift expert, so if you could debug this I will appreciate it."
maybe related to #108

**Comment by riderx** [comment]
Thanks @luca-sharryland, it seems the issue happen in v3 and v4. but definitely the issue on already deleted bundle exist

**Comment by luca-sharryland** [comment]
> Thanks @luca-sharryland, it seems the issue happen in v3 and v4. but definitely the issue on already deleted bundle exist

fix with #109

**Pull request merged**
